"""add_status_to_documents

Revision ID: 426284effc4d
Revises: 534e33cc0746
Create Date: 2026-08-11 15:12:29.696901

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '426284effc4d'
down_revision: str | None = '534e33cc0746'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
